name = "BSON"
uuid = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
version = "0.2.4"

[compat]
julia = "â‰¥ 0.7.0"

[extras]
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Profile"]
